package com.rush.rushaicodemother.orchestration.router;

/** 执行策略和遥测使用的稳定机器可读原因。 */
public enum GenerationRoutingDecisionCode {

    CREATE_TEMPLATE_COVERAGE_GAP,
    CREATE_TEMPLATE_FIRST,
    EXPLICIT_HEAVY_EXPERT,
    TELEMETRY_QUALITY_ESCALATION,
    TELEMETRY_SATURATION_CONTAINMENT,
    AGENT_EDIT_COMPLEXITY,
    LIGHT_EDIT_SCOPE,
    DEFAULT_AGENT_EDIT,
    INTENT_PROFILE_CREATE,
    INTENT_PROFILE_COMPLEX_CREATE,
    INTENT_PROFILE_LIGHT_EDIT,
    INTENT_PROFILE_AGENT_EDIT,
    INTENT_PROFILE_HEAVY_EDIT,
    FALLBACK_HEAVY_EXPERT,
    UNKNOWN
}